export const LANGUAGES = [
    { value: "English", label: "English" },
    { value: "Spanish", label: "Español" },
    { value: "French", label: "Français" },
    { value: "German", label: "Deutsch" },
    { value: "Portuguese", label: "Português" },
    { value: "Italian", label: "Italiano" },
    { value: "Dutch", label: "Nederlands" },
    { value: "Russian", label: "Русский" },
    { value: "Chinese", label: "中文" },
    { value: "Japanese", label: "日本語" },
    { value: "Korean", label: "한국어" },
    { value: "Arabic", label: "العربية" },
    { value: "Hindi", label: "हिन्दी" },
    { value: "Turkish", label: "Türkçe" },
    { value: "Polish", label: "Polski" },
    { value: "Swedish", label: "Svenska" },
    { value: "Norwegian", label: "Norsk" },
    { value: "Danish", label: "Dansk" },
    { value: "Finnish", label: "Suomi" },
    { value: "Greek", label: "Ελληνικά" },
    { value: "Czech", label: "Čeština" },
    { value: "Hungarian", label: "Magyar" },
    { value: "Romanian", label: "Română" },
    { value: "Thai", label: "ไทย" },
    { value: "Vietnamese", label: "Tiếng Việt" },
    { value: "Indonesian", label: "Bahasa Indonesia" },
    { value: "Malay", label: "Bahasa Melayu" },
    { value: "Hebrew", label: "עברית" },
    { value: "Ukrainian", label: "Українська" },
    { value: "Bengali", label: "বাংলা" },
    { value: "Persian", label: "فارسی" },
] as const;

export type LanguageValue = typeof LANGUAGES[number]["value"];
